# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solveqpImpl <- function(H, h, lb, ub, A, Alb, Aub, isFactorized, maxIter, tol, checkPD) {
    .Call(`_qpmadR_solveqpImpl`, H, h, lb, ub, A, Alb, Aub, isFactorized, maxIter, tol, checkPD)
}

